# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-05 17:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wishes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='owner',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
